### ISSUE TITLE
You really should make the towers more rare.

### ISSUE THREAD

**Issue by K0-RR** [RobertSkalko/Dungeons-of-Exile#18]
![2021-04-10_14 53 14](https://user-images.githubusercontent.com/43277609/114270433-9e3cc580-9a0c-11eb-8e7e-b1aaf510ae6f.png)
![image](https://user-images.githubusercontent.com/43277609/116752994-a9c94e00-aa06-11eb-88b0-931c13b51345.png)

**Comment by RobertSkalko** [comment]
I did. They are rare enough for my liking now.
