### ISSUE TITLE
Ticking Block Entity: Delay

### ISSUE THREAD

**Issue by kirkusmaximus** [RobertSkalko/Dungeons-of-Exile#20]
Crashlog: https://paste.ee/p/kAfAM

Seed: 1757666302566687382

Does not appear to always happen. I've had plenty of towers that are happy with me. But once i come upon one it has the same crash log.

Let me know if you need me to run any tests.

**Comment by RobertSkalko** [comment]
Closing as the pastefile logs are deleted. If this is still happening on new versions please make a new issue or update this one.
