### ISSUE TITLE
Loot table issue

### ISSUE THREAD

**Issue by Zano1999** [RobertSkalko/Dungeons-of-Exile#4]
When i edit the loot_table.json file tower stop spawning.

Here my loot_table.json and config file:

LOOT_TABLE: https://pastebin.com/BuarnpL9

CONFIG: https://pastebin.com/eUf1g7FJ

**Comment by RobertSkalko** [comment]
It's not bug if you screwed up the json yourself. Also your config tower separation is much higher, which means its possible you just didnt find them as they are rarer.

**Comment by Zano1999** [comment]
I never say its a bug, the title say: loot_table Issue.
And i searching them with /locate command, it say there is one and i /tp in that position but there is nothing

**Comment by RobertSkalko** [comment]
that second one will be fixed next patch.
