### ISSUE TITLE
Biome checking should be done when adding to biomes, not during structure generation

### ISSUE THREAD

**Issue by TelepathicGrunt** [RobertSkalko/Dungeons-of-Exile#5]
Hello! I was trying to test Dungeons of Exile with my mod World Blender which grabs structures to spawn in its dimension. However, I found that DoE's structures does not spawn in the dimension and did a bit of code digging and came across this:
https://github.com/RobertSkalko/Dungeons-of-Exile/blob/9c7a8bb34036f73502257e74d9b6586f26f459bc/src/main/java/com/robertx22/world_of_exile/world_gen/jigsaw/dungeon/ModDungeonFeature.java#L25-L27

While this isn't the reason why the dungeon doesn't spawn in my dimension, it could cause issues for other mods still. Basically, shouldStartAt is really not suppose to be for biome checking. Instead, the DoE dungeons should be added only to biomes that are not in the beach, ocean, or river category at startup which would mean less checks being done during worldgen and less possible issues.

I'm still looking around to see why the dungeon doesn't spawn in my dimension but hopefully this small change will still help out your mod!

**Comment by RobertSkalko** [comment]
Idk how i did it in currently published version, but in dev I have a config system for dimensions. It's based on a whitelist so my structures only spawn where specificed in my config. It can be seen in my CommonInit class. My library mod contains the dimension and biome config classes, which I didn't yet push to github as I wasn't done with update.

Specifically

` if (ModConfig.get().DUNGEON.isAllowedIn(null, biome, regManager)) {
                        list.get(GenerationStep.Feature.SURFACE_STRUCTURES.ordinal())
                            .add(ModWorldGen.INSTANCE.DUNGEON);
                        setlist.add(() -> ModWorldGen.INSTANCE.CONFIG_DUNGEON);
                    }

`
checks if the structure should be added to the biome, and

    ModConfig.get().DUNGEON.onWorldLoad(world);

deletes the structure from the world if the dimension isn't whitelisted.

**Comment by TelepathicGrunt** [comment]
Ah. I saw there was a dimension entry in the config and whitelisting my dimension in it didn't work. Was a bit confused lol. I'll try it again when the next updates come out!

**Comment by RobertSkalko** [comment]
The dungeon has some extra checks so it doesn't spawn too high, otherwise the entrance spawns on a mountain and the huge blocky dungeon sticks out of the mountain.
